CREATE TABLE CARGO (
ID_CARGO INTEGER,
NOME VARCHAR(30));

 
ALTER TABLE CARGO

ADD PRIMARY KEY (ID_CARGO);


CREATE TABLE FUNCIONARIO (
NOME VARCHAR( 60 ) NOT NULL ,
EMAIL VARCHAR( 60 ) NOT NULL ,
SEXO VARCHAR( 10 ) NOT NULL ,
DDD INT( 2 ) ,
SALARIO numeric(15,2),
TELEFONE VARCHAR ( 8 ) ,
ATIVO VARCHAR(1),
ENDERECO VARCHAR( 70 ) NOT NULL ,
CPF VARCHAR (11) NOT NULL,
CIDADE VARCHAR( 20 ) NOT NULL ,
ESTADO VARCHAR( 2 ) NOT NULL ,
BAIRRO VARCHAR( 20 ) NOT NULL ,
PAIS VARCHAR( 20 ) NOT NULL ,
LOGIN VARCHAR( 12 ) NOT NULL ,
SENHA VARCHAR( 12 ) NOT NULL ,
NEWS VARCHAR( 8 ) ,
ID INT( 200 ) AUTO_INCREMENT ,
UNIQUE (ID ));

 
ALTER TABLE FUNCIONARIO

ADD PRIMARY KEY (CPF);



CREATE TABLE FALTAS (
ID_FUNCIONARIO INTEGER,
DATA_FALTA DATE,
JUSTIFICADA CHAR(1));


ALTER TABLE FALTAS

ADD CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID);


CREATE TABLE NIVEL (
ID_NIVEL INTEGER,
NOME VARCHAR(30));


ALTER TABLE NIVEL

ADD PRIMARY KEY (ID_NIVEL);


CREATE TABLE F_CARGO_NIVEL (
F_CPF VARCHAR(11),
F_ID_CARGO INTEGER,
F_ID_NIVEL INTEGER,
F_DATA DATE);




ALTER TABLE F_CARGO_NIVEL

ADD PRIMARY KEY (F_CPF);



ALTER TABLE F_CARGO_NIVEL

ADD CONSTRAINT FK_F_CARGO FOREIGN KEY (F_ID_CARGO) REFERENCES CARGO (ID_CARGO);


ALTER TABLE F_CARGO_NIVEL

ADD CONSTRAINT FK_F_NIVEL FOREIGN KEY (F_ID_NIVEL) REFERENCES NIVEL (ID_NIVEL);


ALTER TABLE F_CARGO_NIVEL

ADD CONSTRAINT FK_F_CPF FOREIGN KEY (F_CPF) REFERENCES FUNCIONARIO (CPF);


