CREATE  PROCEDURE `DiminuirSalario`(
in P_CPF VARCHAR(11),
in PERCENTUAL INTEGER,
OUT RESULTADO VARCHAR(60))
BEGIN
DECLARE ID_FUNCIONARIO INTEGER;

    SELECT ID FROM FUNCIONARIO 
    WHERE CPF = P_CPF
    INTO ID_FUNCIONARIO;
    
    UPDATE FUNCIONARIO AS FUNC
	SET FUNC.SALARIO = FUNC.SALARIO-SALARIO*(PERCENTUAL/100)
	WHERE FUNC.ID = ID_FUNCIONARIO;
    SET RESULTADO = 'SALARIO REDUZIDO';
 END


