CREATE PROCEDURE `RegistrarFalta`(
PID_FUNCIONARIO INTEGER,
PDATA_FALTA DATE,
PJUSTIFICADA CHAR(1))
BEGIN

   INSERT INTO FALTAS(ID_FUNCIONARIO,DATA_FALTA,JUSTIFICADA)
   VALUES(PID_FUNCIONARIO,PDATA_FALTA,PJUSTIFICADA);
 
END
