CREATE  PROCEDURE `PromoverFuncionario`(
P_CPF VARCHAR(11),
P_NIVEL INTEGER)
BEGIN
DECLARE CPF_FUNCIONARIO VARCHAR(11);
DECLARE DATA_NIVEL DATE;
DECLARE NIVEL_ATUAL INTEGER;

	SELECT 
		FUNCIONARIO.CPF,
        F_CARGO_NIVEL.F_DATA,
        F_CARGO_NIVEL.F_ID_NIVEL
    FROM 
		FUNCIONARIO,
        F_CARGO_NIVEL
    WHERE
		FUNCIONARIO.CPF = F_CARGO_NIVEL.F_CPF AND
		FUNCIONARIO.CPF = P_CPF
    INTO CPF_FUNCIONARIO, DATA_NIVEL,NIVEL_ATUAL ;
    
    IF  NOW() > DATA_NIVEL + INTERVAL '3' year THEN
		IF P_NIVEL = NIVEL_ATUAL+1 THEN
           UPDATE F_CARGO_NIVEL 
           SET F_CARGO_NIVEL.F_ID_NIVEL = P_NIVEL
           WHERE F_CARGO_NIVEL.F_CPF = CPF_FUNCIONARIO;
        END IF;
    END IF ;   
	
END
