CREATE TRIGGER `trabalho2`.`FALTAS_AFTER_INSERT` AFTER INSERT ON `FALTAS` FOR EACH ROW
BEGIN
DECLARE CONTADOR INTEGER;
	SELECT COUNT(FALTAS.JUSTIFICADA) FROM FALTAS
	WHERE FALTAS.ID_FUNCIONARIO = NEW.ID_FUNCIONARIO 
	AND FALTAS.JUSTIFICADA = 'N'
    
	INTO CONTADOR;
	
    
    IF (CONTADOR >= 5) THEN 
		UPDATE FUNCIONARIO 
        SET FUNCIONARIO.ATIVO = 'N'
        WHERE FUNCIONARIO.ID = NEW.ID_FUNCIONARIO;
    END IF;   

END
