CREATE TABLE INGREDIENTE

(

ID_INGREDIENTE integer NOT NULL,

DESCRICAO character varying,

MEDIDA character varying,

CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE)

);



CREATE TABLE PESSOA

(

ID_PESSOA integer NOT NULL,

NOME character varying,

LOGIN character varying,

SENHA character varying,

CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PESSOA)

);


CREATE TABLE RECEITA

(

ID_RECEITA integer NOT NULL AUTO_INCREMENT,

DATA_ENVIO date,

TITULO character varying,

MODO_PREPARO character varying,

ID_PESSOA integer,

CONSTRAINT PK_RECEITA PRIMARY KEY (ID_RECEITA),

CONSTRAINT FK_PESSOA" FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID_PESSOA)

ON UPDATE NO ACTION ON DELETE NO ACTION

);


CREATE TABLE RECEITA_INGREDIENTE

(

ID_RECEITA integer NOT NULL,

ID_INGREDIENTE integer NOT NULL,

QUANTIDADE double precision,

CONSTRAINT PK_INGREDIENTE_RECEITA PRIMARY KEY (ID_RECEITA, ID_INGREDIENTE),

CONSTRAINT FK_INGREDIENTE FOREIGN KEY (ID_INGREDIENTE)

REFERENCES INGREDIENTE (ID_INGREDIENTE) ON UPDATE NO ACTION ON DELETE NO ACTION,

CONSTRAINT FK_RECEITA FOREIGN KEY (ID_RECEITA)

REFERENCES RECEITA (ID_RECEITA) ON UPDATE NO ACTION ON DELETE NO ACTION

);



CREATE TABLE VOTACAO

(

ID_VOTO integer NOT NULL AUTO_INCREMENT,

NOTA double precision,

ID_PESSOA integer,

ID_RECEITA integer,

CONSTRAINT PK_VOTO PRIMARY KEY (ID_VOTO),

CONSTRAINT FK_PESSOA FOREIGN KEY (ID_PESSOA)

REFERENCES PESSOA (ID_PESSOA) ON UPDATE NO ACTION ON DELETE NO ACTION,

CONSTRAINT FK_RECEITA FOREIGN KEY (ID_RECEITA)

REFERENCES RECEITA (ID_RECEITA) ON UPDATE NO ACTION ON DELETE NO ACTION

);
