CREATE  FUNCTION `MEDIA_NOTA`() RETURNS varchar(100) CHARSET latin1
BEGIN
DECLARE SOMA FLOAT;
DECLARE CONTADOR FLOAT;
DECLARE MEDIA FLOAT;
DECLARE TEMP_MEDIA FLOAT;
DECLARE done INT DEFAULT FALSE;
DECLARE TITULO_RECEITA VARCHAR(100);
DECLARE RECEITA_MAIOR_NOTA VARCHAR(100);
DECLARE CURSOR_MEDIA CURSOR FOR 
		(SELECT RECEITA.TITULO, SUM(VOTACAO.NOTA),count(VOTACAO.ID_RECEITA)
		 FROM VOTACAO , RECEITA
		 WHERE VOTACAO.ID_RECEITA = RECEITA.ID_RECEITA
         AND month(RECEITA.DATA_ENVIO) = month(now())
		 group by VOTACAO.ID_RECEITA);
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
		
        OPEN CURSOR_MEDIA;
        SET TEMP_MEDIA = 0;
        LOOP_MEDIA:LOOP
				FETCH CURSOR_MEDIA  INTO TITULO_RECEITA, SOMA,CONTADOR;
				IF done THEN
					LEAVE LOOP_MEDIA;
				END IF;
                SET MEDIA = SOMA/CONTADOR;
				IF TEMP_MEDIA < MEDIA THEN
					SET TEMP_MEDIA = MEDIA;
                    SET RECEITA_MAIOR_NOTA = TITULO_RECEITA;
                END IF;    
		END LOOP LOOP_MEDIA;
		CLOSE CURSOR_MEDIA;

RETURN RECEITA_MAIOR_NOTA;
END
