CREATE  PROCEDURE `popula_votacao`(
P_PESSOA INTEGER ,
P_RECEITA INTEGER,
P_CONTADOR INTEGER
)
BEGIN
DECLARE CONTADOR INTEGER;
DECLARE TEMP_NOTA INTEGER;
SET CONTADOR = 1;

		MIL: LOOP
			SET TEMP_NOTA =  FLOOR(5 + (RAND() * 6));

			INSERT INTO VOTACAO(NOTA,ID_PESSOA,ID_RECEITA)

			values(TEMP_NOTA,P_PESSOA,P_RECEITA);

			SET CONTADOR = CONTADOR+1;

			IF CONTADOR >P_CONTADOR THEN
				LEAVE MIL;
			END IF;    

		END LOOP;
 

END

