CREATE temporary TABLE INGREDIENTE_RECEITA(
QUANTIDADE float,
DESCRICAO VARCHAR(60));

SET @DESCRICAO = 'OVO';
SET @QUANTIDADE = 2.69;

INSERT INTO INGREDIENTE_RECEITA(QUANTIDADE,DESCRICAO) 
VALUES(@QUANTIDADE,@DESCRICAO);

SELECT * FROM INGREDIENTE_RECEITA;

